### PR TITLE
Lowercase identifier when forming links

### LINKED ISSUE #15: Links Are Broken When Links Include Uppercase Characters
## Current Issue

If the name of the type or the target's name contains upper case characters results in links generated by `docc2html` results in 404 errors.
`docc2html` generates an html page for a taget named `TargetName`, type name `TypeName`, and function name `test` at the following path: `/documentation/targetname/typename/test(_:).html` even though the links embedded in other pages look like this `/documentation/TargetName/TypeName/test(_:).html`.

You can reproduce the issue in the following GitHub Pages based deployment: https://apodini.github.io/Template-Repository/documentation/apodinitemplate/apodinitemplate/index.html
The link to the `greet` function in the HTML page is [`https://apodini.github.io/Template-Repository/documentation/ApodiniTemplate/ApodiniTemplate/greet(_:).html`](https://apodini.github.io/Template-Repository/documentation/ApodiniTemplate/ApodiniTemplate/greet(_:).html) while the HTML page can be found at [`https://apodini.github.io/Template-Repository/documentation/apodinitemplate/apodinitemplate/greet(_:).html`](https://apodini.github.io/Template-Repository/documentation/apodinitemplate/apodinitemplate/greet(_:).html)

## Related Issues 

The issue was first noted in issue #13

### PR DESCRIPTION
**Pull request by 3Qax**
Fixes #15

### CODE REVIEW

File: Sources/DocCHTMLExporter/DZRenderingContext.swift [hunk 1]
```diff
@@ -142,7 +142,9 @@ open class DZRenderingContext {
     return pathToRoot + url
   }
   private func makeRelativeToRoot(_ url: URL) -> String {
-    return makeRelativeToRoot(url.path)
+    // Since identifier (reference URL) is used to form this link
+    // rather than url, path needs to be lowercased to match generated files.
```
Comment (3Qax) [inline Sources/DocCHTMLExporter/DZRenderingContext.swift:146]:
```suggestion
    // Since identifier (reference URL) is used to form links rather than url,
    // it's path needs to be lowercased, as url is, in order to match generated files .
```
